### ISSUE TITLE
Rounding Value

### ISSUE THREAD

**Issue by LaksamanaGuntur** [fadhly-permata/flutter_money_formatter#7]
**Describe the bug**
I get a problem with rounding value

**To Reproduce**
`your sample : `
FlutterMoneyFormatter fmf = FlutterMoneyFormatter(
    amount: 12345678.9012345
);
and output with print(fo.compactNonSymbol); is `12.30M`

`My sample :` 
i change amount with 123**5**5678.9012345 (change number four to five)
and output with print(fo.compactNonSymbol); is `12.40M`

**Expected behavior**
My Expectation is `12.35`

**Screenshots**

<img width="438" alt="Screen Shot 2019-07-29 at 12 26 56" src="https://user-images.githubusercontent.com/31402541/62023676-29a40200-b1fc-11e9-884b-7d654c088716.png">

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Redmi Note 5]
 - OS: [8.1]

Thanks!

**Comment by fadhly-permata** [comment]
**English Version:**
Hi @LaksamanaGuntur, actually this is not part of `flutter_money_formatter`, the rounding results are obtained from the `intl` dependency.

However, as far as I know, rounding will usually use the round-up/round-down method. So if we pay attention, the reason number `12355678.9012345` becomes `12.40M` is, the fourth number is 5, so the rounding method used is definitely using the round-up method.

Remember, the numbers 1,2,3,4 have definitely been rounded-down, and the numbers 5,6,7,8,9 are definitely rounding up.

Maybe if possible, in the next version I will add round-up and round-down features (by ignoring the basic concept of rounding numbers).

**P.S:**
Please re-learn the concept of rounding, and as an additional reference from me, (since you are Indonesian) this is [a good article that discusses rounding numbers](https://www.pinterpandai.com/how-solution-first-age-figures-example-example-resolution/)

---

**Versi Indonesia**
Hi @LaksamanaGuntur , sebetulnya hal ini bukan merupakan bagian dari flutter_money_formatter, hasil pembulatan tersebut didapat dari dependency `intl`.

Namun, sepanjang yang saya tau, pembulatan biasanya akan menggunakan metode pembulatan ke angka terdekat (round-up/round-down). Jadi bila kita perhatikan, alasan angka 12355678.9012345 menjadi 12.40M adalah, Angka ke-empat adalah angka 5, sehingga metode pembulatan yang digunakan sudah pasti menggunakan metode round-up (pembulatan ke-atas).

Ingat, angka 1,2,3,4 sudah pasti mengalami pembulatan round-down,
dan angka 5,6,7,8,9 sudah pasti mengalami pembulatan ke-atas.

Mungkin bila memungkinkan, pada versi berikutnya akan saya tambahkan fitur round-up dan round-down (dengan mengabaikan konsep dasar pembulatan angka).

**N.B:**
Silahkan pelajari kembali konsep pembulatan, dan sebagai referensi tambahan dari saya, (berhubung Anda orang Indonesia) maka ini [artikel bagus yang membahas mengenai pembulatan angka](https://www.pinterpandai.com/cara-aturan-pembulatan-angka-bilangan-contoh-soal-jawaban/)
